export { default as SavingsGroup } from './SavingsGroup'
export { default as SavingsDetail } from './SavingsDetails'
export { default as Login } from './Login'
export { default as HomeWallet } from './HomeWallet'
export { default as NotFound } from './NotFound'
export { default as InternalServerError } from './InternalServerError'
export { default as PaymentsFAI } from './PaymentsFAI'
export { PaymentFaiResult } from './PaymentsFAI/'
export { default as CreditDetail } from './CreditDetail'
export { default as Support } from './Support'
export { default as CreditGroup } from './CreditGroup'
export { default as TarDetail } from './TarDetail'
export { default as ForgetPassword } from './ForgetPassword'
export { default as ValidateDocument } from './ForgetPassword/inc/ValidateDocument'
export { default as MultiPaymentsTDC } from './MultiPaymentsTDC'
export { default as NewPassword } from './ForgetPassword/inc/NewPassword'
export { default as PortfolioPurchase } from './PortfolioPurchase'

export { default as Payments } from './Payments'
export { default as OpeningTDCResult } from './OpeningTDCResult'
export { default as PaymentsResult } from './PaymentsResult'
export { default as ProductsOpening } from './ProductsOpening'
export { default as TdcOpening } from './TdcOpening'
export { default as OpeningCreditCard } from './OpeningCreditCard'

export { default as CreditCardDetail } from './CreditCardDetail'
export { default as ActivateCard } from './ActivateCard'
